# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: Ruby
  password: Ruby_123
  port: 3306
  socket: /var/lib/mysql/mysql.sock
  database: rubyappdb

test:
  <<: *default

production:
  <<: *default
